### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'constructor')

### ISSUE THREAD

**Issue by steve02081504** [MichaelXF/js-confuser#157]
**Describe the bug:**

The program gets crushed

**Config and Small code sample**

Config:

```js
{
  target: "node",
  preset: "high"
}
```

Code:

I can't find a suitable minimal reproduction at the moment :(
Please leave a message if you need jumbo code

**Expected behavior**

The program should output code

**Actual behavior**

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'constructor')
    at StringEncoding.get className (file:///C:/Users/steve02081504/AppData/Local/deno/npm/registry.npmjs.org/js-confuser/1.7.3/dist/transforms/transform.js:105:67)
    at StringEncoding.objectAssign (file:///C:/Users/steve02081504/AppData/Local/deno/npm/registry.npmjs.org/js-confuser/1.7.3/dist/transforms/transform.js:334:48)
    at StringEncoding.replace (file:///C:/Users/steve02081504/AppData/Local/deno/npm/registry.npmjs.org/js-confuser/1.7.3/dist/transforms/transform.js:309:10)
    at file:///C:/Users/steve02081504/AppData/Local/deno/npm/registry.npmjs.org/js-confuser/1.7.3/dist/transforms/string/stringEncoding.js:73:12
    at walk (file:///C:/Users/steve02081504/AppData/Local/deno/npm/registry.npmjs.org/js-confuser/1.7.3/dist/traverse.js:72:7)
    at walk (file:///C:/Users/steve02081504/AppData/Local/deno/npm/registry.npmjs.org/js-confuser/1.7.3/dist/traverse.js:60:15)
    at walk (file:///C:/Users/steve02081504/AppData/Local/deno/npm/registry.npmjs.org/js-confuser/1.7.3/dist/traverse.js:60:15)
    at walk (file:///C:/Users/steve02081504/AppData/Local/deno/npm/registry.npmjs.org/js-confuser/1.7.3/dist/traverse.js:52:13)
    at walk (file:///C:/Users/steve02081504/AppData/Local/deno/npm/registry.npmjs.org/js-confuser/1.7.3/dist/traverse.js:60:15)
    at walk (file:///C:/Users/steve02081504/AppData/Local/deno/npm/registry.npmjs.org/js-confuser/1.7.3/dist/traverse.js:52:13)
```

**Additional context**

no?

**Comment by steve02081504** [comment]
oh nevermind, it's fixed in `[2.0.0-alpha.5](https://www.npmjs.com/package/js-confuser/v/2.0.0-alpha.5)`
