### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'type')

### ISSUE THREAD

**Issue by Krex38** [MichaelXF/js-confuser#41]
**Describe the bug:**

I'm getting TypeError: Cannot read properties of null (reading 'type')

**Config and Small code sample**

Config:

```js
{
  target: "node",
  preset: "high"
}
```

Code:

```js
can't post it there, too big
```

**Expected behavior**

The program should execute the code correctly

**Actual behavior**

```
C:\Users\xxxxxxxxx\Downloads\xxxxxxxxxxxxxxxxxr\Priv\node_modules\js-confuser\dist\transforms\opaquePredicates.js:139
        if (test.type == "Literal") {
                 ^

TypeError: Cannot read properties of null (reading 'type')
    at C:\Users\xxxxxxxxxxx\Downloads\xxxxxxxxxxxxxx\Priv\node_modules\←[4mjs-confuser←[24m\dist\transforms\opaquePredicates.js:139:18
    at C:\Users\xxxxxxxxxxxxxx\Downloads\xxxxxxxxxxxxxx\Priv\node_modules\←[4mjs-confuser←[24m\dist\transforms\transform.js:144:42
    at Array.forEach (<anonymous>)
    at C:\Users\xxxxxxxxxxxxxx\Downloads\xxxxxxxxxxxxxx\Priv\node_modules\←[4mjs-confuser←[24m\dist\transforms\transform.js:144:24
    at walk (C:\Users\xxxxxxxxxxxxxx\Downloads\xxxxxxxxxxxxxx\Priv\node_modules\←[4mjs-confuser←[24m\dist\traverse.js:89:7)
    at walk (C:\Users\xxxxxxxxxxxxxx\Downloads\xxxxxxxxxxxxxx\Priv\node_modules\←[4mjs-confuser←[24m\dist\traverse.js:65:13)
    at walk (C:\Users\xxxxxxxxxxxxxx\Downloads\xxxxxxxxxxxxxx\Priv\node_modules\←[4mjs-confuser←[24m\dist\traverse.js:76:15)
    at walk (C:\Users\xxxxxxxxxxxxxx\Downloads\xxxxxxxxxxxxxx\Priv\node_modules\←[4mjs-confuser←[24m\dist\traverse.js:76:15)
    at walk (C:\Users\xxxxxxxxxxxxxx\Downloads\xxxxxxxxxxxxxx\Priv\node_modules\←[4mjs-confuser←[24m\dist\traverse.js:65:13)
    at walk (C:\Users\xxxxxxxxxxxxxx\Downloads\xxxxxxxxxxxxxx\Priv\node_modules\←[4mjs-confuser←[24m\dist\traverse.js:76:15)
```

**Comment by Krex38** [comment]
Fixed

**Comment by MichaelXF** [comment]
Hi, I'm glad you solved your error. There is an issue and I will get fixing it.

**Comment by Krex38** [comment]
> Hi, I'm glad you solved your error. There is an issue and I will get fixing it.

thx couldn't fix it lmao
